import asyncio
import os
import sys

# Add the current directory to sys.path
sys.path.append(os.getcwd())

from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlalchemy import select

from app.config import settings as app_settings
from app.models import Source, SourceType
from app.models.source import SourceCategory

SOURCES = [
    # --- Existing sources ---
    {
        "name": "TechCabal",
        "domain": "techcabal.com",
        "url": "https://techcabal.com/feed/",
        "logo_url": "https://techcabal.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.90,
        "bias_rating": 0.0,
        "is_active": True,
        "fetch_frequency_minutes": 60,
        "fetch_error_count": 0,
    },
    {
        "name": "Punch Newspapers",
        "domain": "punchng.com",
        "url": "https://punchng.com/feed/",
        "logo_url": "https://punchng.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.85,
        "bias_rating": -0.2,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Nairametrics",
        "domain": "nairametrics.com",
        "url": "https://nairametrics.com/feed/",
        "logo_url": "https://nairametrics.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.FINANCIAL,
        "reliability_score": 0.95,
        "bias_rating": 0.1,
        "is_active": True,
        "fetch_frequency_minutes": 45,
        "fetch_error_count": 0,
    },
    {
        "name": "Vanguard News",
        "domain": "vanguardngr.com",
        "url": "https://www.vanguardngr.com/feed/",
        "logo_url": "https://www.vanguardngr.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.80,
        "bias_rating": 0.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    # --- New sources ---
    {
        "name": "Premium Times",
        "domain": "premiumtimesng.com",
        "url": "https://www.premiumtimesng.com/feed/",
        "logo_url": "https://www.premiumtimesng.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "ThisDay Live",
        "domain": "thisdaylive.com",
        "url": "https://www.thisdaylive.com/feed/",
        "logo_url": "https://www.thisdaylive.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "The Nation Nigeria",
        "domain": "thenationonlineng.net",
        "url": "https://thenationonlineng.net/feed/",
        "logo_url": "https://thenationonlineng.net/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Daily Trust",
        "domain": "dailytrust.com",
        "url": "https://dailytrust.com/feed/",
        "logo_url": "https://dailytrust.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Tribune Online",
        "domain": "tribuneonlineng.com",
        "url": "https://tribuneonlineng.com/feed/",
        "logo_url": "https://tribuneonlineng.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Channels Television",
        "domain": "channelstv.com",
        "url": "https://www.channelstv.com/feed/",
        "logo_url": "https://www.channelstv.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "The Cable",
        "domain": "thecable.ng",
        "url": "https://www.thecable.ng/feed/",
        "logo_url": "https://www.thecable.ng/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Daily Post Nigeria",
        "domain": "dailypost.ng",
        "url": "https://dailypost.ng/feed/",
        "logo_url": "https://dailypost.ng/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Leadership Nigeria",
        "domain": "leadership.ng",
        "url": "https://leadership.ng/feed/",
        "logo_url": "https://leadership.ng/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "The Sun Nigeria",
        "domain": "sunnewsonline.com",
        "url": "https://www.sunnewsonline.com/feed/",
        "logo_url": "https://www.sunnewsonline.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Blueprint Newspaper",
        "domain": "blueprint.ng",
        "url": "https://www.blueprint.ng/feed/",
        "logo_url": "https://www.blueprint.ng/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Independent Nigeria",
        "domain": "independent.ng",
        "url": "https://independent.ng/feed/",
        "logo_url": "https://independent.ng/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "New Telegraph",
        "domain": "newtelegraphng.com",
        "url": "https://newtelegraphng.com/feed/",
        "logo_url": "https://newtelegraphng.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Legit.ng",
        "domain": "legit.ng",
        "url": "https://www.legit.ng/rss/all.rss",
        "logo_url": "https://www.legit.ng/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Ripples Nigeria",
        "domain": "ripplesnigeria.com",
        "url": "https://www.ripplesnigeria.com/feed/",
        "logo_url": "https://www.ripplesnigeria.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Sahara Reporters",
        "domain": "saharareporters.com",
        "url": "https://saharareporters.com/rss.xml",
        "logo_url": "https://saharareporters.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Information Nigeria",
        "domain": "informationng.com",
        "url": "https://www.informationng.com/feed/",
        "logo_url": "https://www.informationng.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Arise News",
        "domain": "arise.tv",
        "url": "https://www.arise.tv/feed/",
        "logo_url": "https://www.arise.tv/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "News Agency of Nigeria (NAN)",
        "domain": "nan.ng",
        "url": "https://www.nan.ng/feed/",
        "logo_url": "https://www.nan.ng/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GOVERNMENT,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "NTA News",
        "domain": "nta.ng",
        "url": "https://www.nta.ng/feed/",
        "logo_url": "https://www.nta.ng/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GOVERNMENT,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Naija Times",
        "domain": "naijatimes.ng",
        "url": "https://naijatimes.ng/feed/",
        "logo_url": "https://naijatimes.ng/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Proshare Nigeria",
        "domain": "proshareng.com",
        "url": "https://www.proshareng.com/rss/news.xml",
        "logo_url": "https://www.proshareng.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.FINANCIAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "The Street Journal Nigeria",
        "domain": "thestreetjournal.org",
        "url": "https://thestreetjournal.org/feed/",
        "logo_url": "https://thestreetjournal.org/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.FINANCIAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Dataphyte",
        "domain": "dataphyte.com",
        "url": "https://www.dataphyte.com/feed/",
        "logo_url": "https://www.dataphyte.com/favicon.ico",
        "type": SourceType.RSS,
        "category": SourceCategory.GENERAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
    {
        "name": "Stears Business",
        "domain": "stears.co",
        "url": "https://www.stears.co",
        "logo_url": "https://www.stears.co/favicon.ico",
        "type": SourceType.WEBSITE,  # No RSS feed available
        "category": SourceCategory.FINANCIAL,
        "reliability_score": 0.89,
        "bias_rating": 2.0,
        "is_active": True,
        "fetch_frequency_minutes": 30,
        "fetch_error_count": 0,
    },
]


async def seed_sources():
    print(f"Connecting to {app_settings.DATABASE_URL}...")
    engine = create_async_engine(app_settings.DATABASE_URL, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as session:
        print(f"Seeding {len(SOURCES)} sources...")
        added = 0
        skipped = 0

        for s_data in SOURCES:
            stmt = select(Source).where(Source.domain == s_data["domain"])
            result = await session.execute(stmt)
            obj = result.scalar_one_or_none()

            if not obj:
                print(f"  [+] Adding:   {s_data['name']} ({s_data['domain']})")
                session.add(Source(**s_data))
                added += 1
            else:
                print(f"  [~] Skipping: {s_data['name']} (already exists)")
                skipped += 1

        await session.commit()
        print(f"\nDone! Added {added} new sources, skipped {skipped} existing.")

    await engine.dispose()


if __name__ == "__main__":
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    asyncio.run(seed_sources())
