"""Add intelligence_report fields

Revision ID: 2f489f5d4dc3
Revises: ffbc71c7f554
Create Date: 2026-03-08 07:43:24.482994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f489f5d4dc3'
down_revision: Union[str, None] = 'ffbc71c7f554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_analysis', sa.Column('executive_summary', sa.Text(), nullable=True))
    op.add_column('topic_analysis', sa.Column('what_you_need_to_know', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('topic_analysis', sa.Column('key_takeaways', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('topic_analysis', sa.Column('drivers_of_story', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('topic_analysis', sa.Column('strategic_implications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('topic_analysis', sa.Column('regional_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('topic_analysis', sa.Column('confidence_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_analysis', 'confidence_score')
    op.drop_column('topic_analysis', 'regional_impact')
    op.drop_column('topic_analysis', 'strategic_implications')
    op.drop_column('topic_analysis', 'drivers_of_story')
    op.drop_column('topic_analysis', 'key_takeaways')
    op.drop_column('topic_analysis', 'what_you_need_to_know')
    op.drop_column('topic_analysis', 'executive_summary')
    # ### end Alembic commands ###
