"""Align topic models with AI pipeline

Revision ID: 1f95ec6f1223
Revises: ee1d379972a4
Create Date: 2026-02-07 19:20:59.771915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f95ec6f1223'
down_revision: Union[str, None] = 'ee1d379972a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_analysis', sa.Column('facts', sa.JSON(), nullable=True))
    op.add_column('topic_analysis', sa.Column('regional_framing', sa.JSON(), nullable=True))
    op.drop_column('topic_analysis', 'key_points')
    op.add_column('topic_sentiment_breakdown', sa.Column('positive', sa.Float(), nullable=False))
    op.add_column('topic_sentiment_breakdown', sa.Column('neutral', sa.Float(), nullable=False))
    op.add_column('topic_sentiment_breakdown', sa.Column('negative', sa.Float(), nullable=False))
    op.drop_column('topic_sentiment_breakdown', 'positive_percentage')
    op.drop_column('topic_sentiment_breakdown', 'negative_percentage')
    op.drop_column('topic_sentiment_breakdown', 'neutral_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_sentiment_breakdown', sa.Column('neutral_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('topic_sentiment_breakdown', sa.Column('negative_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('topic_sentiment_breakdown', sa.Column('positive_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('topic_sentiment_breakdown', 'negative')
    op.drop_column('topic_sentiment_breakdown', 'neutral')
    op.drop_column('topic_sentiment_breakdown', 'positive')
    op.add_column('topic_analysis', sa.Column('key_points', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('topic_analysis', 'regional_framing')
    op.drop_column('topic_analysis', 'facts')
    # ### end Alembic commands ###
