"""Add auth and interaction tables

Revision ID: 5a71d9938315
Revises: c3f5399b9e6d
Create Date: 2026-02-07 20:35:05.917776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a71d9938315'
down_revision: Union[str, None] = 'c3f5399b9e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
