"""add_source_type

Revision ID: f460347a183a
Revises: e7095ef7ab32
Create Date: 2026-02-08 20:18:13.646162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_source_type

Revision ID: f460347a183a
Revises: e7095ef7ab32
Create Date: 2026-02-08 20:18:13.646162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f460347a183a'
down_revision: Union[str, None] = 'e7095ef7ab32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    source_type = sa.Enum('rss', 'api', 'website', name='sourcetype')
    source_type.create(op.get_bind(), checkfirst=True)
    op.add_column('sources', sa.Column('type', source_type, server_default='website', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'type')
    # Drop the enum type
    source_type = sa.Enum('rss', 'api', 'website', name='sourcetype')
    source_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
