"""Add raw_password

Revision ID: 5fef5951804b
Revises: 66232a58b1db
Create Date: 2026-03-06 15:10:43.034753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fef5951804b'
down_revision: Union[str, None] = '66232a58b1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raw_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'raw_password')
    # ### end Alembic commands ###
