"""Add fallback fields to TopicAnalysis

Revision ID: 1a422072da57
Revises: ea8d75730496
Create Date: 2026-03-08 10:39:36.245764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a422072da57'
down_revision: Union[str, None] = 'ea8d75730496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_analysis', sa.Column('sentiment_summary', sa.Text(), nullable=True))
    op.add_column('topic_analysis', sa.Column('framing_overview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_analysis', 'framing_overview')
    op.drop_column('topic_analysis', 'sentiment_summary')
    # ### end Alembic commands ###
