"""add_engagement_count_to_topics

Revision ID: e7dc3e0ff9da
Revises: 57de750a7484
Create Date: 2026-02-17 06:29:17.704371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7dc3e0ff9da'
down_revision: Union[str, None] = '57de750a7484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('engagement_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'engagement_count')
    # ### end Alembic commands ###
