"""add_regional_categorization

Revision ID: 170e872c52d5
Revises: 1337a699952d
Create Date: 2026-03-12 19:40:49.572970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170e872c52d5'
down_revision: Union[str, None] = '1337a699952d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_regional_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('impact', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_regional_categories_region_name'), 'topic_regional_categories', ['region_name'], unique=False)
    op.create_index(op.f('ix_topic_regional_categories_topic_id'), 'topic_regional_categories', ['topic_id'], unique=False)
    op.alter_column('intelligence_cards', 'icon',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('topic_sentiment_breakdown', 'icon',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic_sentiment_breakdown', 'icon',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('intelligence_cards', 'icon',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_topic_regional_categories_topic_id'), table_name='topic_regional_categories')
    op.drop_index(op.f('ix_topic_regional_categories_region_name'), table_name='topic_regional_categories')
    op.drop_table('topic_regional_categories')
    # ### end Alembic commands ###
