"""add_source_category_and_apikey

Revision ID: a2108a0e193f
Revises: f460347a183a
Create Date: 2026-02-08 20:59:14.054768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2108a0e193f'
down_revision: Union[str, None] = 'f460347a183a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create SourceCategory Enum
    source_category = sa.Enum('general', 'government', 'financial', 'social', name='sourcecategory')
    source_category.create(op.get_bind(), checkfirst=True)
    
    # Attempt to add 'social' to SourceType if not exists (Postgres specific)
    op.execute("ALTER TYPE sourcetype ADD VALUE IF NOT EXISTS 'social'")

    op.add_column('sources', sa.Column('category', source_category, server_default='general', nullable=False))
    op.add_column('sources', sa.Column('api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'api_key')
    op.drop_column('sources', 'category')
    
    # Drop SourceCategory
    source_category = sa.Enum('general', 'government', 'financial', 'social', name='sourcecategory')
    source_category.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
