"""5_pillar_schema_upgrade

Revision ID: bd516b2a51d6
Revises: a2108a0e193f
Create Date: 2026-02-13 10:03:41.967934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd516b2a51d6'
down_revision: Union[str, None] = 'a2108a0e193f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_impact_categories_slug'), 'impact_categories', ['slug'], unique=True)
    op.create_table('source_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('tag_type', sa.String(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('verticals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_verticals_slug'), 'verticals', ['slug'], unique=True)
    op.create_table('ai_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('summary_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('bullet_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_takeaway', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_summaries_topic_id'), 'ai_summaries', ['topic_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('collection_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('articles_fetched', sa.Integer(), nullable=False),
    sa.Column('articles_new', sa.Integer(), nullable=False),
    sa.Column('articles_duplicate', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_jobs_source_id'), 'collection_jobs', ['source_id'], unique=False)
    op.create_table('impact_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_metrics_topic_id'), 'impact_metrics', ['topic_id'], unique=False)
    op.create_table('regional_impacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('impact_category_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['impact_category_id'], ['impact_categories.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regional_impacts_impact_category_id'), 'regional_impacts', ['impact_category_id'], unique=False)
    op.create_index(op.f('ix_regional_impacts_topic_id'), 'regional_impacts', ['topic_id'], unique=False)
    op.create_table('source_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_group_id'], ['source_groups.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_group_members_source_group_id'), 'source_group_members', ['source_group_id'], unique=False)
    op.create_index(op.f('ix_source_group_members_source_id'), 'source_group_members', ['source_id'], unique=False)
    op.create_table('topic_perspectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('source_group_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=False),
    sa.Column('stance_summary', sa.Text(), nullable=True),
    sa.Column('key_emphasis', sa.Text(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_group_id'], ['source_groups.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_perspectives_source_group_id'), 'topic_perspectives', ['source_group_id'], unique=False)
    op.create_index(op.f('ix_topic_perspectives_topic_id'), 'topic_perspectives', ['topic_id'], unique=False)
    op.create_table('topic_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_tags_tag_id'), 'topic_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_topic_tags_topic_id'), 'topic_tags', ['topic_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_digest_frequency', sa.String(), nullable=False),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('comment_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_votes_comment_id'), 'comment_votes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_votes_user_id'), 'comment_votes', ['user_id'], unique=False)
    op.create_table('community_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('identified_by', sa.String(), nullable=False),
    sa.Column('display_location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id')
    )
    op.create_table('impact_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regional_impact_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regional_impact_id'], ['regional_impacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_details_regional_impact_id'), 'impact_details', ['regional_impact_id'], unique=False)
    op.create_table('perspective_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_perspective_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['raw_articles.id'], ),
    sa.ForeignKeyConstraint(['topic_perspective_id'], ['topic_perspectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perspective_quotes_topic_perspective_id'), 'perspective_quotes', ['topic_perspective_id'], unique=False)
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_options_poll_id'), 'poll_options', ['poll_id'], unique=False)
    op.create_table('sentiment_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('overall_sentiment', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('emotional_tone', sa.String(), nullable=True),
    sa.Column('key_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entities_mentioned', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['raw_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_analysis_article_id'), 'sentiment_analysis', ['article_id'], unique=False)
    op.create_table('summary_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('old_summary_id', sa.Integer(), nullable=True),
    sa.Column('new_summary_id', sa.Integer(), nullable=False),
    sa.Column('trigger_reason', sa.String(), nullable=False),
    sa.Column('articles_added_count', sa.Integer(), nullable=False),
    sa.Column('content_diff_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_summary_id'], ['ai_summaries.id'], ),
    sa.ForeignKeyConstraint(['old_summary_id'], ['ai_summaries.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_updates_topic_id'), 'summary_updates', ['topic_id'], unique=False)
    op.create_table('youtube_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('embed_code', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['raw_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index(op.f('ix_youtube_videos_video_id'), 'youtube_videos', ['video_id'], unique=False)
    op.add_column('comments', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('upvote_count', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('downvote_count', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('reply_count', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('comments', sa.Column('moderation_status', sa.String(), nullable=False))
    op.drop_index(op.f('ix_comments_article_id'), table_name='comments')
    op.drop_constraint(op.f('comments_article_id_fkey'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'article_id')
    op.add_column('poll_votes', sa.Column('poll_option_id', sa.Integer(), nullable=False))
    op.add_column('poll_votes', sa.Column('ranking', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_poll_votes_poll_option_id'), 'poll_votes', ['poll_option_id'], unique=False)
    op.create_foreign_key(None, 'poll_votes', 'poll_options', ['poll_option_id'], ['id'])
    op.drop_column('poll_votes', 'option_index')
    op.add_column('polls', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.add_column('polls', sa.Column('poll_type', sa.String(), nullable=False))
    op.add_column('polls', sa.Column('closes_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('polls', sa.Column('total_votes', sa.Integer(), nullable=False))
    op.add_column('polls', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_polls_topic_id'), 'polls', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'polls', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'polls', 'topics', ['topic_id'], ['id'])
    op.drop_column('polls', 'options')
    op.add_column('raw_articles', sa.Column('snippet', sa.Text(), nullable=True))
    op.add_column('raw_articles', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('raw_articles', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('raw_articles', sa.Column('language', sa.String(length=10), nullable=False))
    op.add_column('raw_articles', sa.Column('is_duplicate', sa.Boolean(), nullable=False))
    op.add_column('raw_articles', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.add_column('raw_articles', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_raw_articles_content_hash'), 'raw_articles', ['content_hash'], unique=False)
    op.create_foreign_key(None, 'raw_articles', 'raw_articles', ['duplicate_of_id'], ['id'])
    op.add_column('sources', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sources', sa.Column('fetch_frequency_minutes', sa.Integer(), nullable=False))
    op.add_column('sources', sa.Column('last_fetched_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('fetch_error_count', sa.Integer(), nullable=False))
    op.alter_column('topic_analysis', 'facts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('topic_analysis', 'regional_framing',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('topic_articles', sa.Column('is_primary', sa.Boolean(), nullable=False))
    op.add_column('topic_articles', sa.Column('assigned_by', sa.String(), nullable=False))
    op.add_column('topics', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('topics', sa.Column('category', sa.String(), nullable=True))
    op.add_column('topics', sa.Column('status', sa.String(), nullable=False))
    op.add_column('topics', sa.Column('importance_score', sa.Float(), nullable=False))
    op.add_column('topics', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('topics', sa.Column('comment_count', sa.Integer(), nullable=False))
    op.add_column('topics', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('topics', sa.Column('featured_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('topics', sa.Column('first_seen_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('topics', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_topics_category'), 'topics', ['category'], unique=False)
    op.create_index(op.f('ix_topics_importance_score'), 'topics', ['importance_score'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_index(op.f('ix_topics_status'), 'topics', ['status'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verification_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reputation_score', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_active_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'reputation_score')
    op.drop_column('users', 'verification_type')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'role')
    op.drop_column('users', 'location')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_topics_status'), table_name='topics')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_importance_score'), table_name='topics')
    op.drop_index(op.f('ix_topics_category'), table_name='topics')
    op.drop_column('topics', 'metadata')
    op.drop_column('topics', 'first_seen_at')
    op.drop_column('topics', 'featured_at')
    op.drop_column('topics', 'is_featured')
    op.drop_column('topics', 'comment_count')
    op.drop_column('topics', 'view_count')
    op.drop_column('topics', 'importance_score')
    op.drop_column('topics', 'status')
    op.drop_column('topics', 'category')
    op.drop_column('topics', 'slug')
    op.drop_column('topic_articles', 'assigned_by')
    op.drop_column('topic_articles', 'is_primary')
    op.alter_column('topic_analysis', 'regional_framing',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('topic_analysis', 'facts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('sources', 'fetch_error_count')
    op.drop_column('sources', 'last_fetched_at')
    op.drop_column('sources', 'fetch_frequency_minutes')
    op.drop_column('sources', 'metadata')
    op.drop_constraint(None, 'raw_articles', type_='foreignkey')
    op.drop_index(op.f('ix_raw_articles_content_hash'), table_name='raw_articles')
    op.drop_column('raw_articles', 'metadata')
    op.drop_column('raw_articles', 'duplicate_of_id')
    op.drop_column('raw_articles', 'is_duplicate')
    op.drop_column('raw_articles', 'language')
    op.drop_column('raw_articles', 'word_count')
    op.drop_column('raw_articles', 'content_hash')
    op.drop_column('raw_articles', 'snippet')
    op.add_column('polls', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'polls', type_='foreignkey')
    op.drop_constraint(None, 'polls', type_='foreignkey')
    op.drop_index(op.f('ix_polls_topic_id'), table_name='polls')
    op.drop_column('polls', 'created_by_id')
    op.drop_column('polls', 'total_votes')
    op.drop_column('polls', 'closes_at')
    op.drop_column('polls', 'poll_type')
    op.drop_column('polls', 'topic_id')
    op.add_column('poll_votes', sa.Column('option_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'poll_votes', type_='foreignkey')
    op.drop_index(op.f('ix_poll_votes_poll_option_id'), table_name='poll_votes')
    op.drop_column('poll_votes', 'ranking')
    op.drop_column('poll_votes', 'poll_option_id')
    op.add_column('comments', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('comments_article_id_fkey'), 'comments', 'raw_articles', ['article_id'], ['id'])
    op.create_index(op.f('ix_comments_article_id'), 'comments', ['article_id'], unique=False)
    op.drop_column('comments', 'moderation_status')
    op.drop_column('comments', 'is_featured')
    op.drop_column('comments', 'reply_count')
    op.drop_column('comments', 'downvote_count')
    op.drop_column('comments', 'upvote_count')
    op.drop_column('comments', 'content_html')
    op.drop_index(op.f('ix_youtube_videos_video_id'), table_name='youtube_videos')
    op.drop_table('youtube_videos')
    op.drop_index(op.f('ix_summary_updates_topic_id'), table_name='summary_updates')
    op.drop_table('summary_updates')
    op.drop_index(op.f('ix_sentiment_analysis_article_id'), table_name='sentiment_analysis')
    op.drop_table('sentiment_analysis')
    op.drop_index(op.f('ix_poll_options_poll_id'), table_name='poll_options')
    op.drop_table('poll_options')
    op.drop_index(op.f('ix_perspective_quotes_topic_perspective_id'), table_name='perspective_quotes')
    op.drop_table('perspective_quotes')
    op.drop_index(op.f('ix_impact_details_regional_impact_id'), table_name='impact_details')
    op.drop_table('impact_details')
    op.drop_table('community_insights')
    op.drop_index(op.f('ix_comment_votes_user_id'), table_name='comment_votes')
    op.drop_index(op.f('ix_comment_votes_comment_id'), table_name='comment_votes')
    op.drop_table('comment_votes')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_topic_tags_topic_id'), table_name='topic_tags')
    op.drop_index(op.f('ix_topic_tags_tag_id'), table_name='topic_tags')
    op.drop_table('topic_tags')
    op.drop_index(op.f('ix_topic_perspectives_topic_id'), table_name='topic_perspectives')
    op.drop_index(op.f('ix_topic_perspectives_source_group_id'), table_name='topic_perspectives')
    op.drop_table('topic_perspectives')
    op.drop_index(op.f('ix_source_group_members_source_id'), table_name='source_group_members')
    op.drop_index(op.f('ix_source_group_members_source_group_id'), table_name='source_group_members')
    op.drop_table('source_group_members')
    op.drop_index(op.f('ix_regional_impacts_topic_id'), table_name='regional_impacts')
    op.drop_index(op.f('ix_regional_impacts_impact_category_id'), table_name='regional_impacts')
    op.drop_table('regional_impacts')
    op.drop_index(op.f('ix_impact_metrics_topic_id'), table_name='impact_metrics')
    op.drop_table('impact_metrics')
    op.drop_index(op.f('ix_collection_jobs_source_id'), table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_ai_summaries_topic_id'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    op.drop_index(op.f('ix_verticals_slug'), table_name='verticals')
    op.drop_table('verticals')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('source_groups')
    op.drop_index(op.f('ix_impact_categories_slug'), table_name='impact_categories')
    op.drop_table('impact_categories')
    # ### end Alembic commands ###
