"""Add is_backed_up to Polls

Revision ID: ffbc71c7f554
Revises: 5fef5951804b
Create Date: 2026-03-06 16:18:26.740498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbc71c7f554'
down_revision: Union[str, None] = '5fef5951804b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('is_backed_up', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polls', 'is_backed_up')
    # ### end Alembic commands ###
