"""Add ads schema

Revision ID: 1337a699952d
Revises: 1a422072da57
Create Date: 2026-03-09 08:09:53.689876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1337a699952d'
down_revision: Union[str, None] = '1a422072da57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ad_type', sa.Enum('EXTERNAL', 'SPONSOR', 'IMAGE', name='adtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='adstatus'), nullable=False),
    sa.Column('placement_group', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cpm_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpc_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('revenue_generated', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_placement_group'), 'ads', ['placement_group'], unique=False)
    op.create_table('ad_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ad_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('VIEW', 'CLICK', name='eventtype'), nullable=False),
    sa.Column('page_location', sa.String(), nullable=True),
    sa.Column('user_session', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_events_ad_id'), 'ad_events', ['ad_id'], unique=False)
    op.create_index(op.f('ix_ad_events_timestamp'), 'ad_events', ['timestamp'], unique=False)
    op.create_table('ad_external_network',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ad_id', sa.String(length=36), nullable=False),
    sa.Column('network_name', sa.String(), nullable=False),
    sa.Column('ad_size', sa.String(), nullable=True),
    sa.Column('script_code', sa.Text(), nullable=False),
    sa.Column('is_rotating', sa.Boolean(), nullable=True),
    sa.Column('display_on_homepage', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id')
    )
    op.create_table('ad_image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ad_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('ad_size', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id')
    )
    op.create_table('ad_sponsor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ad_id', sa.String(length=36), nullable=False),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('website_link', sa.String(), nullable=True),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_sponsor')
    op.drop_table('ad_image')
    op.drop_table('ad_external_network')
    op.drop_index(op.f('ix_ad_events_timestamp'), table_name='ad_events')
    op.drop_index(op.f('ix_ad_events_ad_id'), table_name='ad_events')
    op.drop_table('ad_events')
    op.drop_index(op.f('ix_ads_placement_group'), table_name='ads')
    op.drop_table('ads')
    # ### end Alembic commands ###
