"""Add analysis_status to Topic

Revision ID: ea8d75730496
Revises: 2f489f5d4dc3
Create Date: 2026-03-08 08:08:08.474579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8d75730496'
down_revision: Union[str, None] = '2f489f5d4dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('analysis_status', sa.String(), server_default='pending', nullable=False))
    op.create_index(op.f('ix_topics_analysis_status'), 'topics', ['analysis_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_analysis_status'), table_name='topics')
    op.drop_column('topics', 'analysis_status')
    # ### end Alembic commands ###
