"""align_schema_with_reference

Revision ID: 57de750a7484
Revises: 2026_02_15_0350
Create Date: 2026-02-17 05:54:44.990285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57de750a7484'
down_revision: Union[str, None] = '2026_02_15_0350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Handle NULL values for category_configs
    op.execute("UPDATE category_configs SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE category_configs SET updated_at = NOW() WHERE updated_at IS NULL")
    
    op.alter_column('category_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('category_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('category_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint(op.f('category_configs_category_key'), 'category_configs', type_='unique')
    op.drop_index(op.f('ix_category_configs_category'), table_name='category_configs')
    op.create_index(op.f('ix_category_configs_category'), 'category_configs', ['category'], unique=True)
    
    # Handle NULL values for intelligence_cards
    op.execute("UPDATE intelligence_cards SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE intelligence_cards SET updated_at = NOW() WHERE updated_at IS NULL")
    
    op.alter_column('intelligence_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('intelligence_cards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint(op.f('intelligence_cards_topic_id_key'), 'intelligence_cards', type_='unique')
    op.drop_index(op.f('ix_intelligence_cards_display_order'), table_name='intelligence_cards')
    op.drop_index(op.f('ix_intelligence_cards_topic_id'), table_name='intelligence_cards')
    op.create_index(op.f('ix_intelligence_cards_topic_id'), 'intelligence_cards', ['topic_id'], unique=True)
    op.drop_constraint(op.f('intelligence_cards_topic_id_fkey'), 'intelligence_cards', type_='foreignkey')
    op.create_foreign_key(None, 'intelligence_cards', 'topics', ['topic_id'], ['id'])
    op.add_column('regional_impacts', sa.Column('impact_category', sa.String(length=50), nullable=True))
    op.add_column('regional_impacts', sa.Column('icon', sa.String(length=10), nullable=True))
    op.add_column('regional_impacts', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('regional_impacts', sa.Column('value', sa.Text(), nullable=False))
    op.add_column('regional_impacts', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('regional_impacts', sa.Column('context', sa.Text(), nullable=True))
    op.alter_column('regional_impacts', 'impact_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
               
    # Handle NULL values for source_perspectives
    op.execute("UPDATE source_perspectives SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE source_perspectives SET updated_at = NOW() WHERE updated_at IS NULL")
    
    op.alter_column('source_perspectives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_perspectives', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint(op.f('source_perspectives_topic_id_fkey'), 'source_perspectives', type_='foreignkey')
    op.create_foreign_key(None, 'source_perspectives', 'topics', ['topic_id'], ['id'])
    
    # Handle NULL values for topic_sentiment_breakdown
    op.execute("UPDATE topic_sentiment_breakdown SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE topic_sentiment_breakdown SET updated_at = NOW() WHERE updated_at IS NULL")
    
    op.alter_column('topic_sentiment_breakdown', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('topic_sentiment_breakdown', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('ix_topic_sentiment_breakdown_dimension_type'), table_name='topic_sentiment_breakdown')
    op.drop_constraint(op.f('topic_sentiment_breakdown_topic_id_fkey'), 'topic_sentiment_breakdown', type_='foreignkey')
    op.create_foreign_key(None, 'topic_sentiment_breakdown', 'topics', ['topic_id'], ['id'])
    op.add_column('topics', sa.Column('subcategories', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('topics', sa.Column('overall_sentiment', sa.String(length=20), nullable=True))
    op.add_column('topics', sa.Column('sentiment_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'sentiment_score')
    op.drop_column('topics', 'overall_sentiment')
    op.drop_column('topics', 'subcategories')
    op.drop_constraint(None, 'topic_sentiment_breakdown', type_='foreignkey')
    op.create_foreign_key(op.f('topic_sentiment_breakdown_topic_id_fkey'), 'topic_sentiment_breakdown', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_topic_sentiment_breakdown_dimension_type'), 'topic_sentiment_breakdown', ['dimension_type'], unique=False)
    op.alter_column('topic_sentiment_breakdown', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('topic_sentiment_breakdown', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'source_perspectives', type_='foreignkey')
    op.create_foreign_key(op.f('source_perspectives_topic_id_fkey'), 'source_perspectives', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.alter_column('source_perspectives', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('source_perspectives', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regional_impacts', 'impact_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('regional_impacts', 'context')
    op.drop_column('regional_impacts', 'severity')
    op.drop_column('regional_impacts', 'value')
    op.drop_column('regional_impacts', 'title')
    op.drop_column('regional_impacts', 'icon')
    op.drop_column('regional_impacts', 'impact_category')
    op.drop_constraint(None, 'intelligence_cards', type_='foreignkey')
    op.create_foreign_key(op.f('intelligence_cards_topic_id_fkey'), 'intelligence_cards', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_intelligence_cards_topic_id'), table_name='intelligence_cards')
    op.create_index(op.f('ix_intelligence_cards_topic_id'), 'intelligence_cards', ['topic_id'], unique=False)
    op.create_index(op.f('ix_intelligence_cards_display_order'), 'intelligence_cards', ['display_order'], unique=False)
    op.create_unique_constraint(op.f('intelligence_cards_topic_id_key'), 'intelligence_cards', ['topic_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('intelligence_cards', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('intelligence_cards', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_category_configs_category'), table_name='category_configs')
    op.create_index(op.f('ix_category_configs_category'), 'category_configs', ['category'], unique=False)
    op.create_unique_constraint(op.f('category_configs_category_key'), 'category_configs', ['category'], postgresql_nulls_not_distinct=False)
    op.alter_column('category_configs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('category_configs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
