"""add social media context

Revision ID: ba1ab87d4de2
Revises: 170e872c52d5
Create Date: 2026-03-15 12:21:22.659469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba1ab87d4de2'
down_revision: Union[str, None] = '170e872c52d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_social_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('content_excerpt', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('engagement_score', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_social_reactions_platform'), 'topic_social_reactions', ['platform'], unique=False)
    op.create_index(op.f('ix_topic_social_reactions_topic_id'), 'topic_social_reactions', ['topic_id'], unique=False)
    op.alter_column('ai_providers', 'daily_budget_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('5.0'))
    op.add_column('topic_analysis', sa.Column('social_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_analysis', 'social_keywords')
    op.alter_column('ai_providers', 'daily_budget_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('5.0'))
    op.drop_index(op.f('ix_topic_social_reactions_topic_id'), table_name='topic_social_reactions')
    op.drop_index(op.f('ix_topic_social_reactions_platform'), table_name='topic_social_reactions')
    op.drop_table('topic_social_reactions')
    # ### end Alembic commands ###
